# Generated by Django 4.2 on 2023-08-15 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderID', models.CharField(max_length=50)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_mobile', models.CharField(max_length=20)),
                ('customer_email', models.CharField(max_length=100)),
                ('document', models.FileField(null=True, upload_to='')),
                ('order_status', models.CharField(max_length=100)),
            ],
        ),
    ]
