# Generated by Django 4.2 on 2023-08-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_order_special_instructions_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='special_instructions',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
