# Generated by Django 4.2 on 2023-08-16 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_order_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_category',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
