# Generated by Django 4.2 on 2023-09-04 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_assignment_delete_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='payment',
        ),
    ]
