# Generated by Django 4.2 on 2023-09-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_temp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temp',
            name='document',
            field=models.FileField(null=True, upload_to='temp/'),
        ),
    ]
