# Generated by Django 4.2 on 2023-09-05 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_temp_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='document',
            field=models.FileField(null=True, upload_to='assignments/'),
        ),
    ]
