# Generated by Django 4.2 on 2023-09-07 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_assignment_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='temp',
        ),
        migrations.AddField(
            model_name='assignment',
            name='payment',
            field=models.FileField(null=True, upload_to='a_payments/'),
        ),
    ]
