# Generated by Django 4.2 on 2023-09-08 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_delete_temp_assignment_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='delivery_address',
            field=models.CharField(default='None', max_length=1000),
        ),
    ]
