# Generated by Django 4.2 on 2023-09-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_assignment_delivery_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderID', models.CharField(max_length=50)),
                ('order_category', models.CharField(default='None', max_length=100)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_mobile', models.CharField(max_length=20)),
                ('customer_email', models.CharField(max_length=100)),
                ('customer_school', models.CharField(max_length=100)),
                ('special_instructions', models.CharField(default='None', max_length=1000)),
                ('document', models.FileField(null=True, upload_to='records/')),
                ('payment', models.FileField(null=True, upload_to='r_payments/')),
                ('order_status', models.CharField(default='None', max_length=100)),
                ('order_date', models.CharField(default='None', max_length=100)),
                ('delivery_address', models.CharField(default='None', max_length=1000)),
            ],
        ),
    ]
